### PR TITLE
chore(master): release 0.7.0-rc1

### PR DESCRIPTION
**Pull request by Mause**
:robot: I have created a release *beep* *boop*
---

### Features

* support sqlalchemy 2.0 ([fe6be80](https://github.com/Mause/duckdb_engine/commit/fe6be8034aa0d3cdfce03f67cf885eafe3dd9d64))

### Miscellaneous Chores

* release 0.7.0-rc1 ([691fdf9](https://github.com/Mause/duckdb_engine/commit/691fdf918ff3caee21395ab35a1a7840a8a7f833))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by Mause** [comment]
:robot: Release is at https://github.com/Mause/duckdb_engine/releases/tag/v0.7.0-rc1 :sunflower:

**Comment by Mause** [comment]
@edublancas @cpcloud are you two able to sanity check this release candidate over the next couple of days by any chance?

**Comment by cpcloud** [comment]
Yep. I can give it a go today!

**Comment by edublancas** [comment]
sure, I'll give it a try!

**Comment by cpcloud** [comment]
@Mause Thanks for getting the RC out!

 was able to get all of the ibis duckdb test suite to pass except for two tests which I believe are unrelated to duckdb-engine (see the second bit below).

Here's what happened.

1. Initially 12/1296 tests failed. 10/12 were failing because of various tables missing, which I believe is due to [the new-connection requirement](https://github.com/Mause/duckdb_engine/issues/388#issuecomment-1406742421). Switching to `StaticPool` addressed the issue.
2. There appear to be some floating point differences in results. I believe these are due to some changes on the sqlalchemy side around numeric type inference for literals. I don't think this is related to duckdb-engine, because we saw similar failures when making our trino backend work with sqlalchemy 2.

**Comment by Mause** [comment]
@cpcloud thanks for having a look!

With regards to your first point, I ended up choosing a route that required me to copy some code out of SQLAlchemy, but shouldn't have caused the new-connection requirement I initially thought was required - if you're able to provide a list of the tests that are failing, or a small reproduction, I'd be more than happy to have a look

Your theory for point two sounds about right, but I'd still like to investigate if you have a small reproduction on hand?

**Comment by cpcloud** [comment]
I created a branch (https://github.com/cpcloud/ibis/tree/duckdb-engine-sqlalchemy-fails) that contains an up-to-date lockfile which you can use to run tests:

For 1:

```
$ pytest 'ibis/backends/tests/test_generic.py::test_memtable_bool_column[duckdb]'
```

For 2 (numerics):

```
$ pytest 'ibis/backends/tests/test_numeric.py::test_complex_math_functions_columns[duckdb-log2]'
```

**Pull request merged**
